using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EnumFast;

/// <summary>
/// An incremental Roslyn source generator: for every enum marked
/// <c>[EnumExtensions]</c> it emits a static class with a <c>ToStringFast()</c>
/// extension — a plain <c>switch</c> that returns the member name as a literal.
///
/// The payoff is that the built-in <see cref="System.Enum.ToString()"/> is
/// reflection-based (it looks the value up in the enum's metadata on every call);
/// the generated switch compiles to a jump/compare and is many times faster,
/// with zero allocation. It also generates an <c>IsDefined()</c> that avoids the
/// boxing and reflection of <c>Enum.IsDefined</c>.
///
/// It is an <see cref="IIncrementalGenerator"/>, so it participates in Roslyn's
/// caching pipeline and only re-runs for enums that actually changed.
/// </summary>
[Generator]
public sealed class EnumExtensionsGenerator : IIncrementalGenerator
{
    private const string AttributeName = "EnumFast.EnumExtensionsAttribute";

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace EnumFast
        {
            /// <summary>Mark an enum to have fast extension methods generated.</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Enum)]
            internal sealed class EnumExtensionsAttribute : global::System.Attribute { }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Make the marker attribute available to user code before analysis runs.
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("EnumExtensionsAttribute.g.cs", AttributeSource));

        // Find every enum annotated with the attribute, project it to a small
        // value model, and generate one file per enum.
        var enums = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeName,
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: static (ctx, _) => Extract((INamedTypeSymbol)ctx.TargetSymbol))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(enums, static (spc, model) =>
            spc.AddSource(model!.Name + "Extensions.g.cs", Generate(model!)));
    }

    private sealed record EnumModel(string? Namespace, string Name, string FullName,
                                    bool IsPublic, ImmutableArray<string> Members);

    private static EnumModel? Extract(INamedTypeSymbol symbol)
    {
        // Deduplicate members that share an underlying value (aliases) — two
        // switch arms with the same value would be a compile error.
        var seen = new System.Collections.Generic.HashSet<object?>();
        var members = ImmutableArray.CreateBuilder<string>();
        foreach (var f in symbol.GetMembers().OfType<IFieldSymbol>())
        {
            if (!f.HasConstantValue) continue;
            if (seen.Add(f.ConstantValue)) members.Add(f.Name);
        }

        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();
        var full = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var isPublic = symbol.DeclaredAccessibility == Accessibility.Public;
        return new EnumModel(ns, symbol.Name, full, isPublic, members.ToImmutable());
    }

    private static string Generate(EnumModel m)
    {
        var access = m.IsPublic ? "public" : "internal";
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (m.Namespace is not null)
        {
            sb.AppendLine($"namespace {m.Namespace}");
            sb.AppendLine("{");
        }
        sb.AppendLine($"    {access} static class {m.Name}Extensions");
        sb.AppendLine("    {");

        // ToStringFast
        sb.AppendLine($"        /// <summary>Allocation-free, reflection-free replacement for {m.Name}.ToString().</summary>");
        sb.AppendLine($"        public static string ToStringFast(this {m.FullName} value)");
        sb.AppendLine("            => value switch");
        sb.AppendLine("            {");
        foreach (var name in m.Members)
            sb.AppendLine($"                {m.FullName}.{name} => nameof({m.FullName}.{name}),");
        sb.AppendLine("                _ => value.ToString(),");
        sb.AppendLine("            };");
        sb.AppendLine();

        // IsDefined
        sb.AppendLine($"        /// <summary>True iff the value is a declared member of {m.Name}.</summary>");
        sb.AppendLine($"        public static bool IsDefined(this {m.FullName} value)");
        sb.AppendLine("            => value switch");
        sb.AppendLine("            {");
        foreach (var name in m.Members)
            sb.AppendLine($"                {m.FullName}.{name} => true,");
        sb.AppendLine("                _ => false,");
        sb.AppendLine("            };");

        sb.AppendLine("    }");
        if (m.Namespace is not null) sb.AppendLine("}");
        return sb.ToString();
    }
}
