<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ZeroCsv/ZeroCsv.csproj" />
  </ItemGroup>

</Project>
